### ISSUE TITLE
[Bug]: ローカル版エディタで「使えないLoRAを使えるように変換」をキャンセルしても、変換がスタートしてエラーになる

### ISSUE THREAD

**Issue by serick4126** [Zuntan03/EasyPromptAnime#2]
コミット:e10348f

ローカル版エディタのメニューから「使えないLoRAを使えるように変換」を実行し、ファイル選択ダイアログボックスでキャンセルをクリックしても変換がスタートしてしまい、ファイルが選択されていないためエラーになります。

SRC_PATH: "F:\EasyPromptAnime"
MERGED_PATH: "F:\EasyPromptAnime-merged.safetensors"
DEST_PATH: "F:\EasyPromptAnime\animatediff-cli-prompt-travel\data\lora\EasyPromptAnime.safetensors"
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
loading SD model: F:\EasyPromptAnime\animatediff-cli-prompt-travel\data\models\sd\xxmix9realistic_v40.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
loading: F:\EasyPromptAnime
Traceback (most recent call last):
  File "F:\EasyPromptAnime\sd-scripts\networks\merge_lora.py", line 357, in <module>
    merge(args)
  File "F:\EasyPromptAnime\sd-scripts\networks\merge_lora.py", line 246, in merge
    merge_to_sd_model(text_encoder, unet, args.models, args.ratios, merge_dtype)
  File "F:\EasyPromptAnime\sd-scripts\networks\merge_lora.py", line 65, in merge_to_sd_model
    lora_sd, _ = load_state_dict(model, merge_dtype)
  File "F:\EasyPromptAnime\sd-scripts\networks\merge_lora.py", line 17, in load_state_dict
    sd = torch.load(file_name, map_location="cpu")
  File "F:\EasyPromptAnime\sd-scripts\venv\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "F:\EasyPromptAnime\sd-scripts\venv\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "F:\EasyPromptAnime\sd-scripts\venv\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'F:\\EasyPromptAnime'
続行するには何かキーを押してください . . .

**Comment by Zuntan03** [comment]
不具合の報告、ありがとうございます。
修正しました。
